### ISSUE TITLE
Section numbers are not matching correctly

### ISSUE THREAD

**Issue by PatrickAlphaC** [Cyfrin/Updraft#120]
<img width="169" alt="Screenshot 2024-05-22 at 12 20 06 PM" src="https://github.com/Cyfrin/Updraft/assets/54278053/6b1f8c00-29da-4e2f-961b-baa2f6153e7c">
<img width="290" alt="Screenshot 2024-05-22 at 12 20 21 PM" src="https://github.com/Cyfrin/Updraft/assets/54278053/a36f1219-f416-4743-9c95-9da5c2f4d91a">

The section numbers are wrong in some areas. Can we please fix?

https://updraft.cyfrin.io/courses/blockchain-basics: This is correct.

https://updraft.cyfrin.io/courses/blockchain-basics: This is wrong. It should be numbers 1 -> 4 starting with Simple Storage being Section 1.

https://updraft.cyfrin.io/courses/foundry: This is wrong. It should be numbers 1 -> 4 starting with Foundry Simple Storage

https://updraft.cyfrin.io/courses/advanced-foundry: This is wrong. It should be 1 -> 6 starting with develop an ERC20. 

https://updraft.cyfrin.io/courses/security: This is correct.

**Comment by solhosty** [comment]
Oh I think for Simple Storage that is under https://updraft.cyfrin.io/courses/solidity

I'll fix indexing now on Syllabus and do a re-order.

**Comment by solhosty** [comment]
Had to adjust some logic in the front-end with numbering sections for an immediate fix. 

Security: 
![image](https://github.com/Cyfrin/Updraft/assets/104146303/7f23bf07-5327-45f2-9100-4f145646847c)
Solidity: 
![image](https://github.com/Cyfrin/Updraft/assets/104146303/455ab4e5-50ec-43b4-85a0-9fffa0b500ae)
Foundry Fundamentals: 
![image](https://github.com/Cyfrin/Updraft/assets/104146303/164df63c-45fe-4f8f-8391-af9a49894c0b)
Advanced Foundry: 
![image](https://github.com/Cyfrin/Updraft/assets/104146303/95bcd274-bb82-4383-b0bb-9750a2ea50a6)

**Comment by cromewar** [comment]
Issue solved, closing this.
