### ISSUE TITLE
Written Content Account Abstraction Lesson 1 Introduction

### ISSUE THREAD

**Issue by SupaMega24** [Cyfrin/Updraft#134]
### Purpose

Create a written lesson for the introductory lesson of Account Abstraction in the Advanced Foundry course. This lesson will cover the basics of account abstraction, its benefits, and how it is implemented in Ethereum and zkSync. It should be written as a companion the the video lecture. It will include:

1. Overview and lesson objectives
2. Problems account abstraction has solved
3. Two entry points: `EntryPoint.so`l and zkSync
4. Optional add-ons for `EntryPoint.sol`
5. Questions for review

The lesson will also include relevant images from the video lesson to help support and give cohesion to the process of learning.

**Comment by cromewar** [comment]
@PatrickAlphaC may be is worth to add your video as a lesson.

@SupaMega24 thanks for the recommendation, check this out: https://www.youtube.com/watch?v=PZ8svp68NXM&t=3s

**Comment by SupaMega24** [comment]
@cromewar Thank you. I wrote it based of of Patrick's lesson.

**Comment by ciaranightingale** [comment]
Going to close this issue as the written content for the added lessons is in the pipeline - thanks for flagging
