### ISSUE TITLE
Incorrect URL source of images

### ISSUE THREAD

**Issue by TheWilsonGlobal** [Cyfrin/Updraft#167]
All links of Image are broken caused by outdate
Please kindly fix it

![Screen Shot 2024-08-16 at 09 28 23](https://github.com/user-attachments/assets/a6c2dc2e-bbbe-4345-b20a-eada6626aac7)

**Comment by EngrPips** [comment]
Hey @TheWilsonGlobal, Thanks for the contribution and this will attended to appropriately as soon as possible

**Comment by cromewar** [comment]
Hello @TheWilsonGlobal, yes, this is a wide Markdown problem platform. We will correct that soon. Thanks for reporting.

**Comment by TheWilsonGlobal** [comment]
Hello @cromewar,
Many thanks for fast respond. Instead of waiting Markdown platform updates.
We just correct this is issue by adding `/static` at the beginning of all URLs image source
Then issue will be fixed completely

https://github.com/TheWilsonGlobal/Updraft/blob/main/courses/advanced-foundry/3-develop-defi-protocol/1-defi-introduction/%2Bpage.md

![Screen Shot 2024-08-17 at 08 12 22](https://github.com/user-attachments/assets/3b504b5c-6b09-401d-87d7-3b2f0788bc78)
![Screen Shot 2024-08-17 at 08 12 51](https://github.com/user-attachments/assets/7ec90513-667e-4019-a4c7-f0c44407f23b)
