### ISSUE TITLE
Image render issue in Written Lessons of Smart Contract Security Course

### ISSUE THREAD

**Issue by deepakA18** [Cyfrin/Updraft#170]
Not a single image which is added to the written lessons readme file is rendering at the frontend side.

Instead the entire image tag snippet is rendered:

![img_issue](https://github.com/user-attachments/assets/81e7d1e6-15ff-4202-adb0-fe92f4183aa7)

**Comment by EngrPips** [comment]
Hello @deepakA18, Thanks for pointing this out, and it will attended to appropriately as soon as possible.

**Comment by cromewar** [comment]
Hello @deepakA18 , this is a platform wide problem and we are working on fixing this as soon as possible.

Thanks for the report.
