### ISSUE TITLE
Remix HTML link in Solidity course written lesson 4 is not rendering on Brave browser

### ISSUE THREAD

**Issue by alex-pakalniskis** [Cyfrin/Updraft#180]
The written lesson for Solidity Smart Contract Development course "4-setting-up-your-first-contract" is not rendering the Remix link correctly in the Updraft UI (showing raw HTML instead). Please see attached screenshot and links. 

<img width="1370" alt="image" src="https://github.com/user-attachments/assets/3a9abec7-b5a6-46a7-8d61-e591109980fa">

Link to page in Updraft: https://updraft.cyfrin.io/courses/solidity/simple-storage/create-solidity-smart-contract?lesson_format=transcript

Link to page in GitHub repository: https://github.com/Cyfrin/Updraft/blob/main/courses/solidity/1-simple-storage/4-setting-up-your-first-contract/%2Bpage.md

**Comment by EngrPips** [comment]
Hello @alex-pakalniski, Thanks for this contribution. This will be attended to appropriately as soon as possible.

**Comment by Equious** [comment]
@EngrPips could you open a PR for this one? Adjust the formatting for the link from HTML to markdown [](), should work better that way.

**Comment by EngrPips** [comment]
Alright, I will take that on.

**Comment by cromewar** [comment]
@EngrPips I'm closing this issue here, but please tag me on the PR you send for that change.

**Comment by EngrPips** [comment]
Noted @cromewar
