### ISSUE TITLE
Typo and grammar fixes

### ISSUE THREAD

**Issue by Beefy-py** [Cyfrin/Updraft#194]
In the first course, "Blockchain Basics", I found typos and grammar issues while following along.
I fixed them locally and will make a PR for it.

**Comment by EngrPips** [comment]
Hello, @Beefy-py, Thanks for the contribution. This will be addressed appropriately as soon as possible.

**Comment by cromewar** [comment]
I saw you sent a PR with this changes, so I'm closing this issue.

Thanks for spending time contribution though @Beefy-py
