### ISSUE TITLE
Images not rendering on written lessons in Blockchain Basics course

### ISSUE THREAD

**Issue by geraldwenzel** [Cyfrin/Updraft#197]
The images are not rendering for the [Setting up Metamask for Ethereum Transactions](https://updraft.cyfrin.io/courses/blockchain-basics/basics/metamask-setup-making-your-first-transaction?lesson_format=transcript) written lesson.

The same behavior exists on other written lessons in the Blockchain Basics course.

**Comment by geraldwenzel** [comment]
Issue has already been reported.

**Comment by EngrPips** [comment]
Thanks for figuring that out @geraldwenzel.
