### ISSUE TITLE
False statement in Solidity Math video

### ISSUE THREAD

**Issue by geraldwenzel** [Cyfrin/Updraft#211]
The **Solidity Smart Contract Development / Section 3: Fund Me / 11. Solidity Math** video at 1:12 incorrectly claims:  
`1e18 * 1e18 = 1e38`. 

The correct statement is: `1e18 * 1e18 = 1e36`.

**Comment by EngrPips** [comment]
Thanks for this contribution, @geraldwenzel. This will be addressed appropriately as soon as possible.

**Comment by Equious** [comment]
Clarification update appended to lesson. Thanks for the contribution!
