### ISSUE TITLE
Foundry Fundamental's Lottery Quiz has typo

### ISSUE THREAD

**Issue by gin** [Cyfrin/Updraft#231]
`setup()` should be `setUp()`

![Screenshot 2024-10-08 at 10 09 17 PM](https://github.com/user-attachments/assets/1c28c24b-8b18-40a1-ab1a-8ebeceaf9113)

If `setup()`, Foundry fails to run:

![Screenshot 2024-10-08 at 10 11 03 PM](https://github.com/user-attachments/assets/a2fc03a4-f1b1-4e51-a284-be29bd9f0e32)

I'm unable to find where this typo is in Cyfrin's GitHub repositories.
Maybe someone from Cyfrin can fix it?

**Comment by EngrPips** [comment]
Hello, @gin, Thanks for this contribution. It will be addressed appropriately as soon as possible.

**Comment by Equious** [comment]
Fix applied.
