### ISSUE TITLE
Suggestion: Precision language in NFTs Collections Intro quiz's question 9

### ISSUE THREAD

**Issue by gin** [Cyfrin/Updraft#234]
Suggestion:
Update quiz question to
"9. Which of the following code snippets correctly tests if an address's **NFT** balance is 1?"
from
"9. Which of the following code snippets correctly tests if an address's balance is 1?"

Reasoning:
In https://updraft.cyfrin.io/courses/advanced-foundry/how-to-create-an-NFT-collection/quiz-nfts-collection-intro
the quiz question "9. Which of the following code snippets correctly tests if an address's balance is 1?"
assumes NFT balance because it is a lesson about NFTs. However, balance can be native token balance or NFT balance.
Colloquially, "balance" would be assumed to be native token's balance by default.

**Comment by Equious** [comment]
Yup, agreed. Adjustment made to verbiage and pushed to prod.
