### ISSUE TITLE
Advanced Foundry's DeFi intro has missing image

### ISSUE THREAD

**Issue by gin** [Cyfrin/Updraft#237]
Image is missing in https://updraft.cyfrin.io/courses/advanced-foundry/develop-defi-protocol/defi-introduction?lesson_format=transcript

![Screenshot 2024-10-15 at 10 18 05 AM](https://github.com/user-attachments/assets/4beb7c00-4a48-43c4-a810-99dddc2cc45f)

In the written lesson's Markdown, filepath shows the filename as `defi-introduction4.PNG`

When looking at https://github.com/Cyfrin/Updraft/tree/main/static/foundry-defi/1-defi-introduction
`defi-introduction4.PNG` does not exist.

Is this image under a different name on Cyfrin's server or shall we remove this image from the written lesson?

**Comment by Equious** [comment]
Was looking for what this may have been and came up empty handed. Probably fair to remove if you want to submit a PR.
