### ISSUE TITLE
Some UX problem in the New Updraft Website

### ISSUE THREAD

**Issue by felixoder** [Cyfrin/Updraft#242]
Hello @PatrickAlphaC 

First, thank you for creating such an engaging and interactive course—I'm really enjoying the learning path!

I wanted to bring a minor issue to your attention regarding the dark mode toggle behavior. Specifically, after toggling to dark mode on a page and navigating to a different page or route, the mode unexpectedly reverts back to light mode.
Expected Behavior

The dark or light mode preference should persist across navigation, retaining the user-selected setting until manually toggled back.
Steps to Reproduce

Here’s a 

https://github.com/user-attachments/assets/415b1d01-ee68-4672-9f7a-7b346b2a6352

demonstrating the issue. In the video, I switched to dark mode after completing a quiz. However, upon navigating to the next lesson, the mode automatically switched back to light mode.
Environment

    Browser: Firefox
    Operating System: Ubuntu

I’m not sure if this is the right place to submit this issue, but I thought I’d raise it here for visibility. Please let me know if I can provide additional details or if there's another channel to report this.

Thank you again for your fantastic work on this course!

**Comment by EngrPips** [comment]
Hello @felixoder, This type of issue should reported on Discord https://discord.gg/cyfrin , You should use the #platform-issues channel to report any issues you have while using the cyfrin platform. This channel is more for reporting issues in any of the course codebases, not the course platform.

**Comment by felixoder** [comment]
Got that @EngrPips

**Comment by PatrickAlphaC** [comment]
Going to close for now, thank you!
