### ISSUE TITLE
Advanced Foundry, DeFi Stablecoin: Missing images in "23. Create the collateral redeem handler" written lesson

### ISSUE THREAD

**Issue by gin** [Cyfrin/Updraft#245]
In https://updraft.cyfrin.io/courses/advanced-foundry/develop-defi-protocol/defi-handler-redeeming-collateral
there are 2 missing images in the written lesson. The section is about minting which is the next lesson. However, when looking at the next lesson, the content is very different so it might not be the same images as the next lesson (not a simple update to the image filepaths). 

When looking at https://github.com/Cyfrin/Updraft/tree/main/static/foundry-defi/21-defi-handler-redeem-collateral there are only 2 images, so it is not a filename issue.

Should the last paragraph of this written lesson be removed?
<img width="1677" alt="Screenshot 2024-10-30 at 9 05 41 PM" src="https://github.com/user-attachments/assets/ac2a7430-51ec-4707-97d0-49d0e0f9421f">

**Comment by EngrPips** [comment]
Hello, @gin, Thanks for this contribution. This will be attended to as soon as possible.

**Comment by Equious** [comment]
Hey! I cannot find these images or the context of their use here. If you want to submit that PR to remove the last paragraph, we'll get it merged in. Thank you!
