### ISSUE TITLE
The keyboard shortcuts window appear without displaying the keys

### ISSUE THREAD

**Issue by HemaDeviU** [Cyfrin/Updraft#272]
<img width="1125" alt="Screenshot 2024-12-10 at 12 16 55 PM" src="https://github.com/user-attachments/assets/b41a9ae7-f3bc-4a3d-b280-973993f3c847">
Upon opening the Cyfrin courses page, a new window shows the introduction of shortcut keys.
However, the image does not display the exact keys accurately and only shows an outline.

**Comment by EngrPips** [comment]
Hello @HemaDeviU, Thanks for this report, but the report will get more attention on the Cyfrin official Discord server https://discord.gg/F27kWAuH .  Please open a ticket on the discord server and choose updraft platform when asked to select a platform.

**Comment by Equious** [comment]
Support ticket opened in Discord.
