### ISSUE TITLE
The site is not working 

### ISSUE THREAD

**Issue by divineat123** [Cyfrin/Updraft#289]
When ever am on the site it’s like I can’t do anything the videos aren’t playing nothing is working on the site please can you see to this

**Comment by EngrPips** [comment]
Hello @divineat123, are you still facing this issue?

**Comment by Equious** [comment]
You may have to check your connection or investigate your internet speed. The site is up and functional with no issue reported elsewhere. You can verify your route using a service such as https://downforeveryoneorjustme.com/
