### ISSUE TITLE
CONTRIBUTING.md file is empty!

### ISSUE THREAD

**Issue by kamuikatsurgi** [Cyfrin/Updraft#54]
If it is not yet made, can I contribute? @PatrickAlphaC @Equious

**Comment by kamuikatsurgi** [comment]
Can I work on it?

**Comment by PatrickAlphaC** [comment]
@kamuikatsurgi if you'd like to make the file, that would be a great starting point :)

**Comment by solhosty** [comment]
hey @kamuikatsurgi, just following up here

**Comment by kamuikatsurgi** [comment]
> hey @kamuikatsurgi, just following up here 

Hey! I guess I must have missed patrick's comment. I was just pointing out that the contributing.md file is empty. I wouldn't want to work on it rn, got some tasks on hand. You can assign it to anyone else.

**Comment by PatrickAlphaC** [comment]
Fixed https://github.com/Cyfrin/Updraft/pull/95
