### ISSUE TITLE
The lesson completion status reverts.

### ISSUE THREAD

**Issue by alfheimrShiven** [Cyfrin/Updraft#76]
As I mark a lesson complete, the ✅ icon shows up but then reverts, as a result of which the lesson completion status remains incomplete.

**Comment by solhosty** [comment]
Hey @alfheimrShiven do you mind sharing a video of this process via Loom?

**Comment by CrystallineButterfly** [comment]
Hey there @solhosty I also noticed this bug, the input buttons for the courses completion is not responsive anymore, may be bug introduced accidentally when adding the subtitles features, upon re-deployment as that is when the change occurred, the vercel deployment/deployment method used after that is probably the source from my experience ✍️

- Here is screen shot (mind my basic arrows 😂 issues with loom)  = 
![Bub-web2](https://github.com/Cyfrin/Updraft/assets/95975209/490c217d-222d-49c1-b8bc-070fa5cc471a)

All the best - K42 👽

**Comment by alfheimrShiven** [comment]
@solhosty PFA:
https://github.com/Cyfrin/Updraft/assets/50408041/0720e418-73a6-4e6c-91fc-5ed95d883f83

**Comment by solhosty** [comment]
I'll take a look here later today @alfheimrShiven @CrystallineButterfly . Thank you both for reporting with specific info, it's very much appreciated. 

I'll update here when a resolution is in production 🙏🏻 .

**Comment by CrystallineButterfly** [comment]
Hey @solhosty

- Thank you for the update ✅
- I am happy you found the source 🙏

All the best always- K 💎

**Comment by alfheimrShiven** [comment]
Awesome. Thanks for the update @solhosty . Cheers!

**Comment by PatrickAlphaC** [comment]
I think this is all set?
