### ISSUE TITLE
Chainlink aggregatorV3 interface is now in the `shared` folder

### ISSUE THREAD

**Issue by PatrickAlphaC** [Cyfrin/Updraft#96]

**Comment by PatrickAlphaC** [comment]
We need to:
- Update it in all the written lessons 
- Add it to the updates section of all the videos

**Comment by Kilo-Loco** [comment]
How can https://github.com/Cyfrin/Updraft/pull/82 be updated to address this issue?

**Comment by PatrickAlphaC** [comment]
This is a great start! But we need to add it to the updates section of Updraft as well. It looks like we don't have the Updates in the open sourced section yet 😕 <br><br>Working on it…
